


<div class="col-12" id="homebg">
<h3>Whatever it takes</h3>
               <h1>Quit Quitting</h1>
               <a href="#premium" class="btn btn-outline-light btn-lg" id="premiumbtn">Premium Program</a>

<div class="col-12" id="newsletterdiv">
    <h4>Subscribe to our newsletter: </h4>
    <form id="newsform" >
    <input type="email" id="newsinput" name="email"  class="form-control" placeholder="your email" />
    <button id="newsbtn" class="btn btn-outline-light " type="submit">Subscribe</button>
    </form>
</div>



</div>












