<!------------------------- KONTAKT POCETAK ------------------>

<!--Contact us  start-->
<div class="col12">
<div id="contact" class="offset5">

  <div class="container" id="contactc">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header text-white" id="cus"><i class="fa fa-envelope"></i> Contact us.
                </div>
                <div class="card-body" id="contactdiv">
                    <form>
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" required>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control" id="message" rows="6" required></textarea>
                        </div>
                        <div class="mx-auto">
                        <button type="submit" id="contactbtn" class="btn btn-primary text-right">Submit</button></div>
                    </form>
                </div>
            </div>
        </div>

        
        <div class="col-12 col-sm-4">
            <div class="card bg-light mb-3">
                <div class="card-header bg-dark text-white text-uppercase"><i class="fa fa-home"></i> Address</div>
                <div class="card-body" id="infodiv">
                    <p>Vukovarska ulica 76</p>
                    <p>31000 Osijek</p>
                    <p>Croatia</p>
                    <p>Email : quitqutting@gmail.com</p>
                    <p>Tel. +385 31 885 300</p>
                    <div id="mapsdiv">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2793.802653296092!2d18.6942581157691!3d45.55429533544779!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475ce7b7a4863703%3A0x7d460db03f3c2923!2sVukovarska%20ul.%2076%2C%2031000%2C%20Osijek!5e0!3m2!1shr!2shr!4v1614208353478!5m2!1shr!2shr" height="300" width="100%"  style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                        </div>

                </div>

            </div>
        </div>
        
            


    </div>
</div> 

</div>
</div>
<!--Contact us over-->





<!------------------------- KONTAKT KRAJ ------------------>