<meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=App::config('nazivApp')?></title>
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/bootstrap.css">
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/style.css">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <link href="//db.onlinewebfonts.com/c/d57f07611622b9f467c979bc144b50bd?family=Gunplay" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="/public/img/logo.png">