<nav class="navbar navbar-expand-lg navbar-dark navbar" id="navbar">
        <div class="container-fluid">
          <a class="navbar-brand float-left" href="#"><img src="/public/img/navbarlogo.png" id="xy" alt="logo"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 125px;">
              <li class="nav-item">
                <a class="nav-link active" id="xy" aria-current="page" href="<?=App::config('url')?>"><?=App::config('nazivApp')?></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" id="xy" aria-current="page" href="<?=App::config('url')?>index/premium">Premium</a>
              </li>
              <li class="nav-item dropdown" id="drop">
                <a class="nav-link dropdown-toggle" id="xy" href="<?=App::config('url')?>index/treneri" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Trainers
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Conditioning</a></li>
                  <li><a class="dropdown-item" href="#">Power</a></li>
                  <li><a class="dropdown-item" href="#">Maintain</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link active" id="xy" aria-current="page" href="<?=App::config('url')?>index/trening">Workouts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" id="xy" aria-current="page" href="<?=App::config('url')?>index/klijenti">Clients</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" id="xy" aria-current="page" href="<?=App::config('url')?>index/kontakt">Contact</a>
              </li>              
               
            </ul>
            <form id="searchform" class="d-flex">
              <input class="form-control me-2 schform" type="search" id="xy" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" id="searchbtn" type="submit">Search</button>
            </form>
              
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <div id="dashboarddiv">
                
              <?php if(isset($_SESSION['autoriziran'])): ?>
        <li id="imeli" class="nav-item"><a class="nav-link active" href="<?=App::config('url')?>nadzornaploca/index"><?=$_SESSION['autoriziran']->Ime?> <?=$_SESSION['autoriziran']->Prezime?></a></li>
        <?php endif;?>
              
                </div>

              <li class="nav-item" id="loginbtn">
              <?php if(!isset($_SESSION['autoriziran'])): ?>
                <a class="nav-link active" id="autorizacija" aria-current="page" href="<?=App::config('url')?>index/login">Login</a>
                <?php else: ?>
                  <div id="logout1">
                  <a class="nav-link active"  href="<?=App::config('url')?>index/logout">
                    Logout
        </a>
                </div>
                  <?php endif;?>
              </li> 
              </ul>

          </div>
        </div>
      </nav>