

<!--Footer start-->

<footer class="text-light" id="footercontact">
  <div class="container">
      <div class="row">
          <div class="col-md-3 col-lg-4 col-xl-3">
              <h5>About</h5>
              <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
              <p class="mb-0">
                  Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
              </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto" id="footera">
              <h5>Partners</h5>
              <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
              <ul class="list-unstyled">
                  <li><a href="https://5percentnutrition.com/" target="_blank">5%Nutrition™</a></li>
                  <li><a href="https://www.underarmour.com/" target="_blank">Under Armour</a></li>
                  <li><a href="https://www.proteka.hr/" target="_blank">Proteka</a></li>
                  <li><a href="https://www.bmfitgear.com/" target="_blank">BMfitgear</a></li>
              </ul>
          </div>

          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto" id="footera">
              <h5>Socials</h5>
              <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
              <ul class="list-unstyled">
                  <li><a href="">Facebook</a></li>
                  <li><a href="">Instagram</a></li>
                  <li><a href="">Youtube</a></li>
                  <li><a href="">Twitter</a></li>
              </ul>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3">
              <h5>Contact</h5>
              <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
              <ul class="list-unstyled">
                  <li><i class="fa fa-home mr-2"></i> Quit Quitting</li>
                  <li><i class="fa fa-envelope mr-2"></i> quitquitting@example.com</li>
                  <li><i class="fa fa-phone mr-2"></i> +385 31 885 300</li>
                  
              </ul>
          </div>
          <div class="col-12 copyright mt-3">
              <p class="float-left">
                  <a href="#">Back to top</a>
              </p>
              
          </div>
      </div>
  </div>
</footer>

<!--Footer over-->