<div class="container col-12" id="novitrenerforma">
<form class="log-in-form" 
    action="<?=App::config('url')?>trener/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog trenera</h4>
  <label class="trenernovoinfo">Ime<br>
    <input type="text" name="ime" value="<?=$trener->ime?>">
  </label>
  <br>
  <label class="trenernovoinfo">Prezime <br>
    <input type="text"  name="prezime" value="<?=$trener->prezime?>">
  </label>
  <br>
  <label class="trenernovoinfo">Iskustvo <br>
    <input type="text" name="iskustvo" value="<?=$trener->iskustvo?>">
  </label>
  <br>
  
  
  <label class="trenernovoinfo">Vrsta <br>
    <input type="text" name="vrsta" value="<?=$trener->vrsta?>">
  </label>


  
 
 <p id="dodajb"><input type="submit" class="button expanded dodajbtn" value="Dodaj"></input></p>
<?=$poruka?>
</form>
</div>